package floobits.actions;

import com.intellij.openapi.actionSystem.AnAction;
import com.intellij.openapi.actionSystem.AnActionEvent;
import floobits.utilities.Flog;
import floobits.utilities.IntelliUtils;

import java.awt.*;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;


public class CompleteSignup extends AnAction {
    public void actionPerformed(AnActionEvent e) {
        String url = IntelliUtils.getCompleteSignUpURL(e.getProject());
        if (url == null) {
            return;
        }
        try {
            URI uri = new URI(url);
            Desktop.getDesktop().browse(uri);
        } catch (IOException error) {
            Flog.error(error);
        } catch (URISyntaxException error) {
            Flog.error(error);
        }
    }
    public void update (AnActionEvent e) {
        e.getPresentation().setEnabled(IntelliUtils.isAutoGenerated());
    }
}
