package floobits.actions;

import com.intellij.openapi.actionSystem.AnAction;
import com.intellij.openapi.actionSystem.AnActionEvent;
import com.intellij.openapi.project.Project;
import floobits.FloobitsPlugin;
import floobits.common.BrowserOpener;
import floobits.common.interfaces.IContext;
import floobits.utilities.Flog;
import floobits.utilities.IntelliUtils;

import java.net.URI;
import java.net.URISyntaxException;


public class CompleteSignup extends AnAction {
    public void actionPerformed(AnActionEvent e) {
        String url = IntelliUtils.getCompleteSignUpURL(e.getProject());
        if (url == null) {
            return;
        }
        Project project = e.getProject();
        FloobitsPlugin plugin = FloobitsPlugin.getInstance(project);
        IContext context = plugin.context;
        try {
            URI uri = new URI(url);
            BrowserOpener.getInstance().openInBrowser(uri, "Click here to complete sign up.", context);
        } catch (URISyntaxException error) {
            Flog.error(error);
        }
    }
    public void update (AnActionEvent e) {
        e.getPresentation().setEnabled(IntelliUtils.isAutoGenerated());
    }
}
